version: 2

project_name: secretharbor

before:
  hooks:
    - go mod tidy
    - go run ./cmd/gen-man man/man1

builds:
  - id: shb
    binary: shb
    main: ./cmd/shb
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/secretharbor/secretharbor/internal/cli.Version={{ .Version }}

  - id: secretharbor
    binary: secretharbor
    main: ./cmd/secretharbor
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/secretharbor/secretharbor/internal/cli.Version={{ .Version }}

archives:
  - id: default
    name_template: "secretharbor_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - shb
      - secretharbor
    files:
      - README.md
      - LICENSE*
      - man/man1/*
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  extra_files:
    - glob: scripts/install.sh
    - glob: scripts/install.ps1
