.TH SHB-HELP 1 "October 2026" "SecretHarbor 0.4.0-prod" "SecretHarbor Manual"
.SH NAME
shb-help \- Show CLI documentation
.SH SYNOPSIS
\fBshb help [command]\fR
.SH DESCRIPTION
Displays general usage or command-specific reference manual.
.SH EXAMPLES
.TP
$ \fBshb help\fR
.TP
$ \fBshb help run\fR
.TP
$ \fBshb help config\fR
.TP
$ \fBshb help policy\fR
.TP
$ \fBshb help doctor\fR
.SH SEE ALSO
shb(1)
.SH WEBSITE
https://secretharbor.dev
